[0m20:16:35.548517 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb1205d9720>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb11f735ab0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb11f735a50>]}


============================== 20:16:35.551348 | 273e6a03-e651-4cae-8bc1-09b3f1f2781d ==============================
[0m20:16:35.551348 [info ] [MainThread]: Running with dbt=1.9.4
[0m20:16:35.552193 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/meta/.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt run --select stagging', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m20:16:35.552709 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/meta/projets-m1-ia/bigdata-architecture-lab/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:16:35.553703 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.075689584, "process_in_blocks": "24", "process_kernel_time": 0.079778, "process_mem_max_rss": "94944", "process_out_blocks": "8", "process_user_time": 1.336295}
[0m20:16:35.554175 [debug] [MainThread]: Command `dbt run` failed at 20:16:35.554068 after 0.08 seconds
[0m20:16:35.554572 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb1205d9720>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb11f736170>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb11f735ab0>]}
[0m20:16:35.554979 [debug] [MainThread]: Flushing usage events
[0m20:16:35.909485 [debug] [MainThread]: An error was encountered while trying to flush usage events
